service: serverless-poc
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline # Adicione esta linha para incluir o plugin
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function
  - serverless-appsync-plugin


appSync:
    name: appsync-poc-api
    authentication:
      type: API_KEY
    schema: 'schema.graphql'
    dataSources:
      getUsers:
        type: 'AWS_LAMBDA'
        config:
          function:
            timeout: 30
            handler: src/functions/users/handler.main
    resolvers:
      getUsers:
        kind: UNIT
        type: Query
        field: getUsers
        dataSource: getUsers



functions:
  getUsers:
    handler: src/functions/users/handler.main
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:us-east-1:875968654243:table/users"
    events:
      - http:
          path: users
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
