service: serverless-poc
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline # Adicione esta linha para incluir o plugin
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function
  - serverless-appsync-plugin


custom:
  appsync:
    mappingTemplates:
      - type: Query
        request: false
        response: false
        dataSource: myLambdaSource
        field: getUsers

functions:
  getUsers:
    handler: src/functions/users/handler.main
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:us-east-1:875968654243:table/users"
    events:
      - http:
          path: users
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
