service: serverless-poc
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline # Adicione esta linha para incluir o plugin
  - serverless-plugin-typescript

functions:
  getUsers:
    handler: src/functions/users/handler.main
    events:
      - http:
          path: users
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
